server:
  port: 8761
spring:
  application:
    name: eureka-serve
eureka:
  server:
    enable-self-preservation: false # #是否开启自我保护模式，默认为true。
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: false
